# Generated by Django 5.1.5 on 2025-03-13 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_slug'),
    ]

    operations = [
        migrations.RunSQL("""
                INSERT INTO store_collection (title)
                Values('collection1')""", 
                """delete from store_collection where title ='collection1' """)
    ]

